// This file will be auto-generated by Supabase CLI
// Run: npm run db:generate-types
// For now, we define a placeholder type

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string
          shopify_product_id: number
          title: string
          description: string | null
          description_html: string | null
          handle: string | null
          sku_label: string | null
          vendor: string | null
          product_type: string | null
          tags: string[] | null
          status: string
          shopify_status: string | null
          shopify_published_at: string | null
          metadata: Json | null
          created_at: string
          updated_at: string
          last_synced_at: string | null
          google_drive_folder_path: string | null
        }
        Insert: {
          id?: string
          shopify_product_id: number
          title: string
          description?: string | null
          description_html?: string | null
          handle?: string | null
          sku_label?: string | null
          vendor?: string | null
          product_type?: string | null
          tags?: string[] | null
          status?: string
          shopify_status?: string | null
          shopify_published_at?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
          last_synced_at?: string | null
          google_drive_folder_path?: string | null
        }
        Update: {
          id?: string
          shopify_product_id?: number
          title?: string
          description?: string | null
          description_html?: string | null
          handle?: string | null
          sku_label?: string | null
          vendor?: string | null
          product_type?: string | null
          tags?: string[] | null
          status?: string
          shopify_status?: string | null
          shopify_published_at?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
          last_synced_at?: string | null
          google_drive_folder_path?: string | null
        }
      }
      product_variants: {
        Row: {
          id: string
          product_id: string
          shopify_variant_id: number
          sku: string | null
          title: string | null
          price: number | null
          compare_at_price: number | null
          weight: number | null
          weight_unit: string | null
          dimensions: Json | null
          inventory_quantity: number | null
          position: number | null
          option1: string | null
          option2: string | null
          option3: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          shopify_variant_id: number
          sku?: string | null
          title?: string | null
          price?: number | null
          compare_at_price?: number | null
          weight?: number | null
          weight_unit?: string | null
          dimensions?: Json | null
          inventory_quantity?: number | null
          position?: number | null
          option1?: string | null
          option2?: string | null
          option3?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          shopify_variant_id?: number
          sku?: string | null
          title?: string | null
          price?: number | null
          compare_at_price?: number | null
          weight?: number | null
          weight_unit?: string | null
          dimensions?: Json | null
          inventory_quantity?: number | null
          position?: number | null
          option1?: string | null
          option2?: string | null
          option3?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      media_buckets: {
        Row: {
          id: string
          product_id: string
          sku_label: string
          bucket_status: string
          storj_path: string
          raw_asset_count: number
          edited_asset_count: number
          published_asset_count: number
          project_file_count: number
          total_asset_count: number
          total_size_bytes: number
          created_at: string
          updated_at: string
          last_upload_at: string | null
          last_publish_at: string | null
          google_drive_folder_path: string | null
          import_batch_id: string | null
          import_completed_at: string | null
        }
        Insert: {
          id?: string
          product_id: string
          sku_label: string
          bucket_status?: string
          storj_path: string
          raw_asset_count?: number
          edited_asset_count?: number
          published_asset_count?: number
          project_file_count?: number
          total_asset_count?: number
          total_size_bytes?: number
          created_at?: string
          updated_at?: string
          last_upload_at?: string | null
          last_publish_at?: string | null
          google_drive_folder_path?: string | null
          import_batch_id?: string | null
          import_completed_at?: string | null
        }
        Update: {
          id?: string
          product_id?: string
          sku_label?: string
          bucket_status?: string
          storj_path?: string
          raw_asset_count?: number
          edited_asset_count?: number
          published_asset_count?: number
          project_file_count?: number
          total_asset_count?: number
          total_size_bytes?: number
          created_at?: string
          updated_at?: string
          last_upload_at?: string | null
          last_publish_at?: string | null
          google_drive_folder_path?: string | null
          import_batch_id?: string | null
          import_completed_at?: string | null
        }
      }
      media_assets: {
        Row: {
          id: string
          media_bucket_id: string
          media_type: string
          workflow_state: string
          file_url: string
          file_key: string
          file_size: number | null
          file_mime_type: string | null
          encoding_handle: string | null
          encoding_video_id: string | null
          encoded_video_url: string | null
          video_metadata: Json | null
          image_metadata: Json | null
          alt_text: string | null
          title: string | null
          original_filename: string
          source_folder_path: string | null
          workflow_category: string
          edited_by: string | null
          edited_at: string | null
          uploaded_by: string | null
          created_at: string
          updated_at: string
          google_drive_file_id: string | null
          google_drive_folder_path: string | null
          import_source: string | null
          import_batch_id: string | null
        }
        Insert: {
          id?: string
          media_bucket_id: string
          media_type: string
          workflow_state: string
          file_url: string
          file_key: string
          file_size?: number | null
          file_mime_type?: string | null
          encoding_handle?: string | null
          encoding_video_id?: string | null
          encoded_video_url?: string | null
          video_metadata?: Json | null
          image_metadata?: Json | null
          alt_text?: string | null
          title?: string | null
          original_filename: string
          source_folder_path?: string | null
          workflow_category: string
          edited_by?: string | null
          edited_at?: string | null
          uploaded_by?: string | null
          created_at?: string
          updated_at?: string
          google_drive_file_id?: string | null
          google_drive_folder_path?: string | null
          import_source?: string | null
          import_batch_id?: string | null
        }
        Update: {
          id?: string
          media_bucket_id?: string
          media_type?: string
          workflow_state?: string
          file_url?: string
          file_key?: string
          file_size?: number | null
          file_mime_type?: string | null
          encoding_handle?: string | null
          encoding_video_id?: string | null
          encoded_video_url?: string | null
          video_metadata?: Json | null
          image_metadata?: Json | null
          alt_text?: string | null
          title?: string | null
          original_filename?: string
          source_folder_path?: string | null
          workflow_category?: string
          edited_by?: string | null
          edited_at?: string | null
          uploaded_by?: string | null
          created_at?: string
          updated_at?: string
          google_drive_file_id?: string | null
          google_drive_folder_path?: string | null
          import_source?: string | null
          import_batch_id?: string | null
        }
      }
      product_media_associations: {
        Row: {
          id: string
          product_id: string
          media_asset_id: string
          variant_id: string | null
          association_type: string
          position: number
          is_published: boolean
          shopify_media_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          media_asset_id: string
          variant_id?: string | null
          association_type: string
          position?: number
          is_published?: boolean
          shopify_media_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          media_asset_id?: string
          variant_id?: string | null
          association_type?: string
          position?: number
          is_published?: boolean
          shopify_media_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          auth_user_id: string
          email: string
          name: string | null
          role: string
          is_active: boolean
          created_at: string
          last_login_at: string | null
        }
        Insert: {
          id?: string
          auth_user_id: string
          email: string
          name?: string | null
          role: string
          is_active?: boolean
          created_at?: string
          last_login_at?: string | null
        }
        Update: {
          id?: string
          auth_user_id?: string
          email?: string
          name?: string | null
          role?: string
          is_active?: boolean
          created_at?: string
          last_login_at?: string | null
        }
      }
      sync_logs: {
        Row: {
          id: string
          sync_type: string
          entity_type: string | null
          entity_id: string | null
          status: string
          error_message: string | null
          details: Json | null
          performed_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          sync_type: string
          entity_type?: string | null
          entity_id?: string | null
          status: string
          error_message?: string | null
          details?: Json | null
          performed_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          sync_type?: string
          entity_type?: string | null
          entity_id?: string | null
          status?: string
          error_message?: string | null
          details?: Json | null
          performed_by?: string | null
          created_at?: string
        }
      }
      audit_logs: {
        Row: {
          id: string
          table_name: string
          record_id: string
          action: string
          old_values: Json | null
          new_values: Json | null
          user_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          table_name: string
          record_id: string
          action: string
          old_values?: Json | null
          new_values?: Json | null
          user_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          table_name?: string
          record_id?: string
          action?: string
          old_values?: Json | null
          new_values?: Json | null
          user_id?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

